### ISSUE TITLE
Class 'Iamstuartwilson\Exception' not found

### ISSUE THREAD

**Issue by minhna** [iamstuartwilson/strava#11]
> PHP Fatal error:  Class 'Iamstuartwilson\Exception' not found in /var/www/html/libraries/iamstuartwilson/strava/src/Iamstuartwilson/StravaApi.php on line 112

Hi,
Thank you for your useful library.
I got this error.

**Comment by mjaschen** [comment]
Hi,

the bug was just fixed! (see pull request #12)

Just update your StravaApi library to version 1.1.2 to get the fixed version.

Marcus
