### ISSUE TITLE
header data?

### ISSUE THREAD

**Issue by clin407** [iamstuartwilson/strava#15]
Is it possible to get header data with your package for all requests? I'm trying to make sure I check headers to get 
X-Ratelimit-Limit and X-Ratelimit-Usage listed here: https://strava.github.io/api/#rate-limiting so I know how to adjust on my end.

**Comment by mjaschen** [comment]
Hi,

access to header data is now available in version 1.2.0.

Just use the `getResponseHeaders()` or `getResponseHeader($header)` methods.

Marcus
