### ISSUE TITLE
Issue getting athlete data.

### ISSUE THREAD

**Issue by cbxiii** [iamstuartwilson/strava#19]
Hello Stuart, 

Thanks for the library. I'm a bit of a beginner with this stuff, and need a push in the right direction for making requests to the API. 

I don't know if I'm setting the access token correctly, and at present I can't get any data back from Strava.

Code:

`<?php
			
		require_once 'StravaApi.php';	
		$clientId = "****";
		$clientSecret = "*****";
		$redirect = "****";
		
		$api = new Iamstuartwilson\StravaApi(
		    $clientId,
		    $clientSecret
		);
		
		$url = $api->authenticationUrl($redirect);
		
		?>
		
		<h4><a href="<?php echo $url; ?>">Request access</a></h4>
		<hr>
		
		<?php
			
		$code = $_GET['code']; 
		$api->tokenExchange($code);
		$api->setAccessToken($accessToken);
		
		$athleteResponse = $api->get( 'athlete', $accessToken );
		print_r($athleteResponse);
		
		?>`

Response:

`Warning: array_merge() [function.array-merge]: Argument #1 is not an array in /nfs/c11/h01/mnt/198966/domains/strava.runawayuk.com/html/StravaApi.php on line 332

Warning: http_build_query() [function.http-build-query]: Parameter 1 expected to be Array or Object. Incorrect value given in /nfs/c11/h01/mnt/198966/domains/strava.runawayuk.com/html/StravaApi.php on line 95
stdClass Object ( [message] => Authorization Error [errors] => Array ( [0] => stdClass Object ( [resource] => Athlete [field] => access_token [code] => invalid ) ) ) ?>`

URL - http://strava.runawayuk.com/

I'm positive it's my fault not yours, but all the same I'm stuck!

Thanks

**Comment by mjaschen** [comment]
Hi,

please try it with omitting the `$accessToken` argument in the get() method call.

`$athleteResponse = $api->get( 'athlete', $accessToken );`

should become:

`$athleteResponse = $api->get('athlete');`

The second argument is for additional parameters, e. g. for pagination settings. It has to be an array.

**Comment by iamstuartwilson** [comment]
Hey @cbxiii, assuming @mjaschen's advice help you out with this, so closing this issue.  Feel free to open a new one if you need some more help :)
