### ISSUE TITLE
License is needed

### ISSUE THREAD

**Issue by mjaschen** [iamstuartwilson/strava#20]
This library has no license information currently, a LICENSE file should be added to the root directory.

MIT license is mentioned in `composer.json` - is that correct?

**Comment by iamstuartwilson** [comment]
@mjaschen generally I consider MIT the most appropriate for this and all truly open source projects on GitHub.  What do you think?

**Comment by mjaschen** [comment]
I completely agree :-)

I'll prepare a pull-request with all the license information later today, ok?

**Comment by iamstuartwilson** [comment]
@mjaschen had a bit of free time this morning :)

**Comment by mjaschen** [comment]
Great, even better :-)

**Comment by mjaschen** [comment]
Everything looks much better now with a license file ;-) Thanks, @iamstuartwilson
