### ISSUE TITLE
webhook strava

### ISSUE THREAD

**Issue by Geovanek** [iamstuartwilson/strava#25]
Would implement the webhook functionality?

**Comment by mjaschen** [comment]
Webhooks require to setup much of the server-side functionality for request parsing, validating, creating responses, etc. I think that's out of focus for a small library like this one.

Any other opinions?

**Comment by iamstuartwilson** [comment]
Hi @Geovanek, does this PR cover what you're asking for? https://github.com/iamstuartwilson/strava/pull/26

**Comment by Geovanek** [comment]
Hello,
I believe so, as soon as I have time to test I give you feedback
Sorry for my english
