### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by Geovanek** [iamstuartwilson/strava#29]
A few weeks later this error began to appear to make the athletes' authorization.
I can not figure out why.

`
												stdClass Object
(
    [message] =&gt; Bad Request
    [errors] =&gt; Array
        (
            [0] =&gt; stdClass Object
                (
                    [resource] =&gt; RequestToken
                    [field] =&gt; code
                    [code] =&gt; invalid
                )

        )

)
														`

**Comment by Geovanek** [comment]
The problem is the new update.
May 25, 2018
GET https://www.strava.com/oauth/authorize returns the scope of the eventual token in the response.

The **Code** is coming with scope together now
EX: 1970128947389014f72f8bc5c&amp;scope=view_private

And the &scope=view_private cause erro on $api->tokenExchange($code[1]);

**Comment by Niellles** [comment]
I am not having any problems with the following code. This seems to be more of an error in the implementation and not so much an issue with this repo. Correct?
```php
$token = $api->tokenExchange($code)->access_token;
$api->setAccessToken($token);
```
