### ISSUE TITLE
Packagist Listing is not Auto-Updating

### ISSUE THREAD

**Issue by mjaschen** [iamstuartwilson/strava#39]
Hi @iamstuartwilson 

After the last release I tagged version 1.4.0. The updated version didn't find its way to [Packagist](https://packagist.org/packages/iamstuartwilson/strava). Updating the library via Composer (which is the preferred way to manage dependencies in PHP these days) requires a correct Packagist listing.

Release updates are no longer pushed to Packagist since the deprecation of “Github Services” at the beginning of this year.

There's an alternative way to inform Packagist about new releases with Github's “Webhooks” feature.

You as the repository owner are the only person who can set up the webhook.

The process is simple:

- go to https://github.com/iamstuartwilson/strava/settings/hooks
- “Add webhook”:
    - Payload URL: https://packagist.org/api/github
    - Content Type: application/json
    - Secret: your Packagist API key (https://packagist.org/profile/ → “Show API Token”)
    - Which events would you like to trigger this webhook? → Just the push event

All future releases should now be pushed to Packagist.

**Comment by iamstuartwilson** [comment]
Thanks for this @mjaschen! Should be updated now with the webhook in place for subsequent releases 👍

**Comment by mjaschen** [comment]
Hi @iamstuartwilson,

thanks for your fixing this! Packagist [lists](https://packagist.org/packages/iamstuartwilson/strava) the most recent version already :-)
