### ISSUE TITLE
Unable to Complete Token Exchange?

### ISSUE THREAD

**Issue by theblanchard** [iamstuartwilson/strava#4]
I have been able to successfully authenticate with my app credentials, but when I try to complete the token exchange, I get a "page not found" error and 
```{"message":"Authorization Error","errors":[{"resource":"Athlete","field":"access_token","code":"invalid"}]}```

A gist with my code is available here: https://gist.github.com/theblanchard/0c2da687e8c3c2d3a89a

I am relatively new to PHP, so any help you can provide is greatly appreciated!

Page after successful auth with API errors:
![dev_error](https://cloud.githubusercontent.com/assets/13232/5967066/88d1e3b6-a7be-11e4-9f41-e870b55b6e1b.png)

Page with successful auth using hardcoded ```access_code``` in URL:
![dev](https://cloud.githubusercontent.com/assets/13232/5967095/bd837822-a7be-11e4-8fae-420b6e300e06.png)

**Comment by iamstuartwilson** [comment]
Hi @theblanchard, sorry its taken so long to get back to you on this.  Could you provide some code examples to support your problem?

Cheers,

Stuart

**Comment by iamstuartwilson** [comment]
@theblanchard on line 53:

```php
$url = $api->authenticationUrl($redirect, $approvalPrompt = 'auto', $scope = null, $state = null);
```

You've left the default values in here.  Try this instead:

```php
$url = $api->authenticationUrl($redirect);
```

**Comment by theblanchard** [comment]
Thanks! I actually figured this out, forgot to close the issue.
