### ISSUE TITLE
Use simpler get example request

### ISSUE THREAD

**Issue by LewisCraik** [iamstuartwilson/strava#44]
I could not see athletes/KOM as one of the queries mentioned on http://developers.strava.com/docs/reference/, maybe it has been removed?

Maybe athletes/stats would be an alternative, also no further parameters are needed, so it is an easier example.

**Comment by mjaschen** [comment]
It's probably a side-effect of the recent changes where several segment-related features (including API access) require a subscription.

**Comment by LewisCraik** [comment]
Has been fixed in #46
